### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [VegaBobo/DSU-Sideloader#75]
ref: https://forum.f-droid.org/t/request-dsu-sideloader-test-a-new-rom-without-wipe-your-current-rom/21958

A quick recipe **metadata/vegabobo.dsusideloader.yml**
```
License: Unknown
SourceCode: https://github.com/VegaBobo/DSU-Sideloader/
IssueTracker: https://github.com/VegaBobo/DSU-Sideloader//issues

RepoType: git
Repo: https://github.com/VegaBobo/DSU-Sideloader.git

Builds:
  - versionName: '2.01'
    versionCode: 6
    commit: 6e244e1ce7abc8ef23765ba7f69f669d0aeb1244
    subdir: app
    gradle:
      - yes
    scandelete:
      - magisk-module/src/main/resources

AutoUpdateMode: None
UpdateCheckMode: Tags
```
...and it's 99.99% reproducible, except for `res/raw/aboutlibraries.json`

Can that .json be sorted or otherwise fixed?
